/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// BatteryDetails
    /// </summary>
    [DataContract]
    public partial class BatteryDetails :  IEquatable<BatteryDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatteryDetails" /> class.
        /// </summary>
        /// <param name="batteryMaterial">batteryMaterial.</param>
        /// <param name="batteryPackaging">batteryPackaging.</param>
        /// <param name="regulatory">regulatory.</param>
        public BatteryDetails(string batteryMaterial = default(string), string batteryPackaging = default(string), string regulatory = default(string))
        {
            this.BatteryMaterial = batteryMaterial;
            this.BatteryPackaging = batteryPackaging;
            this.Regulatory = regulatory;
        }
        
        /// <summary>
        /// Gets or Sets BatteryMaterial
        /// </summary>
        [DataMember(Name="batteryMaterial", EmitDefaultValue=false)]
        public string BatteryMaterial { get; set; }

        /// <summary>
        /// Gets or Sets BatteryPackaging
        /// </summary>
        [DataMember(Name="batteryPackaging", EmitDefaultValue=false)]
        public string BatteryPackaging { get; set; }

        /// <summary>
        /// Gets or Sets Regulatory
        /// </summary>
        [DataMember(Name="regulatory", EmitDefaultValue=false)]
        public string Regulatory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatteryDetails {\n");
            sb.Append("  BatteryMaterial: ").Append(BatteryMaterial).Append("\n");
            sb.Append("  BatteryPackaging: ").Append(BatteryPackaging).Append("\n");
            sb.Append("  Regulatory: ").Append(Regulatory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatteryDetails);
        }

        /// <summary>
        /// Returns true if BatteryDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of BatteryDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatteryDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BatteryMaterial == input.BatteryMaterial ||
                    (this.BatteryMaterial != null &&
                    this.BatteryMaterial.Equals(input.BatteryMaterial))
                ) && 
                (
                    this.BatteryPackaging == input.BatteryPackaging ||
                    (this.BatteryPackaging != null &&
                    this.BatteryPackaging.Equals(input.BatteryPackaging))
                ) && 
                (
                    this.Regulatory == input.Regulatory ||
                    (this.Regulatory != null &&
                    this.Regulatory.Equals(input.Regulatory))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BatteryMaterial != null)
                    hashCode = hashCode * 59 + this.BatteryMaterial.GetHashCode();
                if (this.BatteryPackaging != null)
                    hashCode = hashCode * 59 + this.BatteryPackaging.GetHashCode();
                if (this.Regulatory != null)
                    hashCode = hashCode * 59 + this.Regulatory.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
