/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// ContainerDetails
    /// </summary>
    [DataContract]
    public partial class ContainerDetails :  IEquatable<ContainerDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainerDetails" /> class.
        /// </summary>
        /// <param name="commodityInfo">commodityInfo.</param>
        /// <param name="containerType">containerType.</param>
        /// <param name="packagingType">packagingType.</param>
        public ContainerDetails(List<CommodityInfo> commodityInfo = default(List<CommodityInfo>), string containerType = default(string), string packagingType = default(string))
        {
            this.CommodityInfo = commodityInfo;
            this.ContainerType = containerType;
            this.PackagingType = packagingType;
        }
        
        /// <summary>
        /// Gets or Sets CommodityInfo
        /// </summary>
        [DataMember(Name="commodityInfo", EmitDefaultValue=false)]
        public List<CommodityInfo> CommodityInfo { get; set; }

        /// <summary>
        /// Gets or Sets ContainerType
        /// </summary>
        [DataMember(Name="containerType", EmitDefaultValue=false)]
        public string ContainerType { get; set; }

        /// <summary>
        /// Gets or Sets PackagingType
        /// </summary>
        [DataMember(Name="packagingType", EmitDefaultValue=false)]
        public string PackagingType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContainerDetails {\n");
            sb.Append("  CommodityInfo: ").Append(CommodityInfo).Append("\n");
            sb.Append("  ContainerType: ").Append(ContainerType).Append("\n");
            sb.Append("  PackagingType: ").Append(PackagingType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ContainerDetails);
        }

        /// <summary>
        /// Returns true if ContainerDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ContainerDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContainerDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CommodityInfo == input.CommodityInfo ||
                    this.CommodityInfo != null &&
                    input.CommodityInfo != null &&
                    this.CommodityInfo.SequenceEqual(input.CommodityInfo)
                ) && 
                (
                    this.ContainerType == input.ContainerType ||
                    (this.ContainerType != null &&
                    this.ContainerType.Equals(input.ContainerType))
                ) && 
                (
                    this.PackagingType == input.PackagingType ||
                    (this.PackagingType != null &&
                    this.PackagingType.Equals(input.PackagingType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CommodityInfo != null)
                    hashCode = hashCode * 59 + this.CommodityInfo.GetHashCode();
                if (this.ContainerType != null)
                    hashCode = hashCode * 59 + this.ContainerType.GetHashCode();
                if (this.PackagingType != null)
                    hashCode = hashCode * 59 + this.PackagingType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
