/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// CrossBorderQuotesResponseQuote
    /// </summary>
    [DataContract]
    public partial class CrossBorderQuotesResponseQuote :  IEquatable<CrossBorderQuotesResponseQuote>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CrossBorderQuotesResponseQuote" /> class.
        /// </summary>
        /// <param name="quoteCurrency">quoteCurrency.</param>
        /// <param name="quoteLines">quoteLines.</param>
        /// <param name="totalPrice">totalPrice.</param>
        /// <param name="totalRates">totalRates.</param>
        public CrossBorderQuotesResponseQuote(string quoteCurrency = default(string), List<CrossBorderQuotesResponseQuoteLines> quoteLines = default(List<CrossBorderQuotesResponseQuoteLines>), decimal totalPrice = default(decimal), CrossBorderQuotesResponseTotalRates totalRates = default(CrossBorderQuotesResponseTotalRates))
        {
            this.QuoteCurrency = quoteCurrency;
            this.QuoteLines = quoteLines;
            this.TotalPrice = totalPrice;
            this.TotalRates = totalRates;
        }
        
        /// <summary>
        /// Gets or Sets QuoteCurrency
        /// </summary>
        [DataMember(Name="quoteCurrency", EmitDefaultValue=false)]
        public string QuoteCurrency { get; set; }

        /// <summary>
        /// Gets or Sets QuoteLines
        /// </summary>
        [DataMember(Name="quoteLines", EmitDefaultValue=false)]
        public List<CrossBorderQuotesResponseQuoteLines> QuoteLines { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrice
        /// </summary>
        [DataMember(Name="totalPrice", EmitDefaultValue=false)]
        public decimal TotalPrice { get; set; }

        /// <summary>
        /// Gets or Sets TotalRates
        /// </summary>
        [DataMember(Name="totalRates", EmitDefaultValue=false)]
        public CrossBorderQuotesResponseTotalRates TotalRates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CrossBorderQuotesResponseQuote {\n");
            sb.Append("  QuoteCurrency: ").Append(QuoteCurrency).Append("\n");
            sb.Append("  QuoteLines: ").Append(QuoteLines).Append("\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  TotalRates: ").Append(TotalRates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CrossBorderQuotesResponseQuote);
        }

        /// <summary>
        /// Returns true if CrossBorderQuotesResponseQuote instances are equal
        /// </summary>
        /// <param name="input">Instance of CrossBorderQuotesResponseQuote to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CrossBorderQuotesResponseQuote input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuoteCurrency == input.QuoteCurrency ||
                    (this.QuoteCurrency != null &&
                    this.QuoteCurrency.Equals(input.QuoteCurrency))
                ) && 
                (
                    this.QuoteLines == input.QuoteLines ||
                    this.QuoteLines != null &&
                    input.QuoteLines != null &&
                    this.QuoteLines.SequenceEqual(input.QuoteLines)
                ) && 
                (
                    this.TotalPrice == input.TotalPrice ||
                    (this.TotalPrice != null &&
                    this.TotalPrice.Equals(input.TotalPrice))
                ) && 
                (
                    this.TotalRates == input.TotalRates ||
                    (this.TotalRates != null &&
                    this.TotalRates.Equals(input.TotalRates))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuoteCurrency != null)
                    hashCode = hashCode * 59 + this.QuoteCurrency.GetHashCode();
                if (this.QuoteLines != null)
                    hashCode = hashCode * 59 + this.QuoteLines.GetHashCode();
                if (this.TotalPrice != null)
                    hashCode = hashCode * 59 + this.TotalPrice.GetHashCode();
                if (this.TotalRates != null)
                    hashCode = hashCode * 59 + this.TotalRates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
