/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// ParcelProtectionCreateRequestShipmentInfoParcelInfo
    /// </summary>
    [DataContract]
    public partial class ParcelProtectionCreateRequestShipmentInfoParcelInfo :  IEquatable<ParcelProtectionCreateRequestShipmentInfoParcelInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelProtectionCreateRequestShipmentInfoParcelInfo" /> class.
        /// </summary>
        /// <param name="commodityList">commodityList.</param>
        public ParcelProtectionCreateRequestShipmentInfoParcelInfo(List<ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList> commodityList = default(List<ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList>))
        {
            this.CommodityList = commodityList;
        }
        
        /// <summary>
        /// Gets or Sets CommodityList
        /// </summary>
        [DataMember(Name="commodityList", EmitDefaultValue=false)]
        public List<ParcelProtectionCreateRequestShipmentInfoParcelInfoCommodityList> CommodityList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParcelProtectionCreateRequestShipmentInfoParcelInfo {\n");
            sb.Append("  CommodityList: ").Append(CommodityList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParcelProtectionCreateRequestShipmentInfoParcelInfo);
        }

        /// <summary>
        /// Returns true if ParcelProtectionCreateRequestShipmentInfoParcelInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ParcelProtectionCreateRequestShipmentInfoParcelInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParcelProtectionCreateRequestShipmentInfoParcelInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CommodityList == input.CommodityList ||
                    this.CommodityList != null &&
                    input.CommodityList != null &&
                    this.CommodityList.SequenceEqual(input.CommodityList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CommodityList != null)
                    hashCode = hashCode * 59 + this.CommodityList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
