/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// * LETTER -  Letter. Generates a First-Class label with IMB barcode.  * FRE - Flat rate envelope. * LGENV - Legal flat rate envelope. * LGLFRENV - Padded flat rate envelope. * PFRENV - Small flat rate box. * SFRB - Medium flat rate box. * FRB - Large Flat rate box. * LFRB - DVD box. * DVDBOX - DVDBOX. * VIDEOBOX - Video box. * MLFRB - Military flat raqte box. * RBA - Regional rate box, type A * RBB -  Regional rate box, type B. * PKG - Package (not eligible for special package rate). * LP - Large package. * FLAT - USPS Flat or Large Envelope. * EMMTB - Extended Managed Mail Tray Box. * FTB - Full tray box. * HTB - Half tray box. * SACK - Sack. * FTTB - Flat tub tray. * SOFTPACK - Soft Pack Envelope. * MIX - PMOD Enclosed Package Type. * LTR - Letter for stamp API call. 
    /// </summary>
    /// <value>* LETTER -  Letter. Generates a First-Class label with IMB barcode.  * FRE - Flat rate envelope. * LGENV - Legal flat rate envelope. * LGLFRENV - Padded flat rate envelope. * PFRENV - Small flat rate box. * SFRB - Medium flat rate box. * FRB - Large Flat rate box. * LFRB - DVD box. * DVDBOX - DVDBOX. * VIDEOBOX - Video box. * MLFRB - Military flat raqte box. * RBA - Regional rate box, type A * RBB -  Regional rate box, type B. * PKG - Package (not eligible for special package rate). * LP - Large package. * FLAT - USPS Flat or Large Envelope. * EMMTB - Extended Managed Mail Tray Box. * FTB - Full tray box. * HTB - Half tray box. * SACK - Sack. * FTTB - Flat tub tray. * SOFTPACK - Soft Pack Envelope. * MIX - PMOD Enclosed Package Type. * LTR - Letter for stamp API call. </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ParcelType
    {
        /// <summary>
        /// Enum FLAT for value: FLAT
        /// </summary>
        [EnumMember(Value = "FLAT")]
        FLAT = 1,

        /// <summary>
        /// Enum LETTER for value: LETTER
        /// </summary>
        [EnumMember(Value = "LETTER")]
        LETTER = 2,

        /// <summary>
        /// Enum FRE for value: FRE
        /// </summary>
        [EnumMember(Value = "FRE")]
        FRE = 3,

        /// <summary>
        /// Enum LGENV for value: LGENV
        /// </summary>
        [EnumMember(Value = "LGENV")]
        LGENV = 4,

        /// <summary>
        /// Enum LGLFRENV for value: LGLFRENV
        /// </summary>
        [EnumMember(Value = "LGLFRENV")]
        LGLFRENV = 5,

        /// <summary>
        /// Enum PFRENV for value: PFRENV
        /// </summary>
        [EnumMember(Value = "PFRENV")]
        PFRENV = 6,

        /// <summary>
        /// Enum FRB for value: FRB
        /// </summary>
        [EnumMember(Value = "FRB")]
        FRB = 7,

        /// <summary>
        /// Enum LFRB for value: LFRB
        /// </summary>
        [EnumMember(Value = "LFRB")]
        LFRB = 8,

        /// <summary>
        /// Enum DVDBOX for value: DVDBOX
        /// </summary>
        [EnumMember(Value = "DVDBOX")]
        DVDBOX = 9,

        /// <summary>
        /// Enum VIDEOBOX for value: VIDEOBOX
        /// </summary>
        [EnumMember(Value = "VIDEOBOX")]
        VIDEOBOX = 10,

        /// <summary>
        /// Enum MLFRB for value: MLFRB
        /// </summary>
        [EnumMember(Value = "MLFRB")]
        MLFRB = 11,

        /// <summary>
        /// Enum RBA for value: RBA
        /// </summary>
        [EnumMember(Value = "RBA")]
        RBA = 12,

        /// <summary>
        /// Enum RBB for value: RBB
        /// </summary>
        [EnumMember(Value = "RBB")]
        RBB = 13,

        /// <summary>
        /// Enum LP for value: LP
        /// </summary>
        [EnumMember(Value = "LP")]
        LP = 14,

        /// <summary>
        /// Enum SACK for value: SACK
        /// </summary>
        [EnumMember(Value = "SACK")]
        SACK = 15,

        /// <summary>
        /// Enum SOFTPACK for value: SOFTPACK
        /// </summary>
        [EnumMember(Value = "SOFTPACK")]
        SOFTPACK = 16,

        /// <summary>
        /// Enum MIX for value: MIX
        /// </summary>
        [EnumMember(Value = "MIX")]
        MIX = 17,

        /// <summary>
        /// Enum LTR for value: LTR
        /// </summary>
        [EnumMember(Value = "LTR")]
        LTR = 18,

        /// <summary>
        /// Enum NMLETTER for value: NMLETTER
        /// </summary>
        [EnumMember(Value = "NMLETTER")]
        NMLETTER = 19,

        /// <summary>
        /// Enum NMLTR for value: NMLTR
        /// </summary>
        [EnumMember(Value = "NMLTR")]
        NMLTR = 20,

        /// <summary>
        /// Enum IRRPKG for value: IRRPKG
        /// </summary>
        [EnumMember(Value = "IRRPKG")]
        IRRPKG = 21,

        /// <summary>
        /// Enum SFRB for value: SFRB
        /// </summary>
        [EnumMember(Value = "SFRB")]
        SFRB = 22,

        /// <summary>
        /// Enum EMMTB for value: EMMTB
        /// </summary>
        [EnumMember(Value = "EMMTB")]
        EMMTB = 23,

        /// <summary>
        /// Enum FTB for value: FTB
        /// </summary>
        [EnumMember(Value = "FTB")]
        FTB = 24,

        /// <summary>
        /// Enum FTTB for value: FTTB
        /// </summary>
        [EnumMember(Value = "FTTB")]
        FTTB = 25,

        /// <summary>
        /// Enum HTB for value: HTB
        /// </summary>
        [EnumMember(Value = "HTB")]
        HTB = 26,

        /// <summary>
        /// Enum PACK for value: PACK
        /// </summary>
        [EnumMember(Value = "PACK")]
        PACK = 27,

        /// <summary>
        /// Enum BOX for value: BOX
        /// </summary>
        [EnumMember(Value = "BOX")]
        BOX = 28,

        /// <summary>
        /// Enum SMALLEXPBOX for value: SMALL_EXP_BOX
        /// </summary>
        [EnumMember(Value = "SMALL_EXP_BOX")]
        SMALLEXPBOX = 29,

        /// <summary>
        /// Enum MEDEXPBOX for value: MED_EXP_BOX
        /// </summary>
        [EnumMember(Value = "MED_EXP_BOX")]
        MEDEXPBOX = 30,

        /// <summary>
        /// Enum LGEXPBOX for value: LG_EXP_BOX
        /// </summary>
        [EnumMember(Value = "LG_EXP_BOX")]
        LGEXPBOX = 31,

        /// <summary>
        /// Enum EXTRALGEXPBOX for value: EXTRA_LG_EXP_BOX
        /// </summary>
        [EnumMember(Value = "EXTRA_LG_EXP_BOX")]
        EXTRALGEXPBOX = 32,

        /// <summary>
        /// Enum TUBE for value: TUBE
        /// </summary>
        [EnumMember(Value = "TUBE")]
        TUBE = 33,

        /// <summary>
        /// Enum _25KG for value: 25KG
        /// </summary>
        [EnumMember(Value = "25KG")]
        _25KG = 34,

        /// <summary>
        /// Enum _10KG for value: 10KG
        /// </summary>
        [EnumMember(Value = "10KG")]
        _10KG = 35,

        /// <summary>
        /// Enum PKG for value: PKG
        /// </summary>
        [EnumMember(Value = "PKG")]
        PKG = 36

    }

}
