/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// ParcelProtectionPolicyResponseShipmentDetails
    /// </summary>
    [DataContract]
    public partial class ParcelProtectionPolicyResponseShipmentDetails :  IEquatable<ParcelProtectionPolicyResponseShipmentDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelProtectionPolicyResponseShipmentDetails" /> class.
        /// </summary>
        /// <param name="shipmentDate">shipmentDate.</param>
        /// <param name="shipmentTransactionId">shipmentTransactionId.</param>
        /// <param name="shipmentId">shipmentId.</param>
        /// <param name="parcelTrackingNumber">parcelTrackingNumber.</param>
        /// <param name="carrier">carrier.</param>
        /// <param name="amount">amount.</param>
        /// <param name="packageLength">packageLength.</param>
        /// <param name="packageWidth">packageWidth.</param>
        /// <param name="packageHeight">packageHeight.</param>
        /// <param name="weight">weight.</param>
        /// <param name="zone">zone.</param>
        public ParcelProtectionPolicyResponseShipmentDetails(string shipmentDate = default(string), string shipmentTransactionId = default(string), string shipmentId = default(string), string parcelTrackingNumber = default(string), string carrier = default(string), string amount = default(string), string packageLength = default(string), string packageWidth = default(string), string packageHeight = default(string), string weight = default(string), string zone = default(string))
        {
            this.ShipmentDate = shipmentDate;
            this.ShipmentTransactionId = shipmentTransactionId;
            this.ShipmentId = shipmentId;
            this.ParcelTrackingNumber = parcelTrackingNumber;
            this.Carrier = carrier;
            this.Amount = amount;
            this.PackageLength = packageLength;
            this.PackageWidth = packageWidth;
            this.PackageHeight = packageHeight;
            this.Weight = weight;
            this.Zone = zone;
        }
        
        /// <summary>
        /// Gets or Sets ShipmentDate
        /// </summary>
        [DataMember(Name="shipmentDate", EmitDefaultValue=false)]
        public string ShipmentDate { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentTransactionId
        /// </summary>
        [DataMember(Name="shipmentTransactionId", EmitDefaultValue=false)]
        public string ShipmentTransactionId { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name="shipmentId", EmitDefaultValue=false)]
        public string ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets ParcelTrackingNumber
        /// </summary>
        [DataMember(Name="parcelTrackingNumber", EmitDefaultValue=false)]
        public string ParcelTrackingNumber { get; set; }

        /// <summary>
        /// Gets or Sets Carrier
        /// </summary>
        [DataMember(Name="carrier", EmitDefaultValue=false)]
        public string Carrier { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or Sets PackageLength
        /// </summary>
        [DataMember(Name="packageLength", EmitDefaultValue=false)]
        public string PackageLength { get; set; }

        /// <summary>
        /// Gets or Sets PackageWidth
        /// </summary>
        [DataMember(Name="packageWidth", EmitDefaultValue=false)]
        public string PackageWidth { get; set; }

        /// <summary>
        /// Gets or Sets PackageHeight
        /// </summary>
        [DataMember(Name="packageHeight", EmitDefaultValue=false)]
        public string PackageHeight { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [DataMember(Name="weight", EmitDefaultValue=false)]
        public string Weight { get; set; }

        /// <summary>
        /// Gets or Sets Zone
        /// </summary>
        [DataMember(Name="zone", EmitDefaultValue=false)]
        public string Zone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParcelProtectionPolicyResponseShipmentDetails {\n");
            sb.Append("  ShipmentDate: ").Append(ShipmentDate).Append("\n");
            sb.Append("  ShipmentTransactionId: ").Append(ShipmentTransactionId).Append("\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  ParcelTrackingNumber: ").Append(ParcelTrackingNumber).Append("\n");
            sb.Append("  Carrier: ").Append(Carrier).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  PackageLength: ").Append(PackageLength).Append("\n");
            sb.Append("  PackageWidth: ").Append(PackageWidth).Append("\n");
            sb.Append("  PackageHeight: ").Append(PackageHeight).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  Zone: ").Append(Zone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParcelProtectionPolicyResponseShipmentDetails);
        }

        /// <summary>
        /// Returns true if ParcelProtectionPolicyResponseShipmentDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ParcelProtectionPolicyResponseShipmentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParcelProtectionPolicyResponseShipmentDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipmentDate == input.ShipmentDate ||
                    (this.ShipmentDate != null &&
                    this.ShipmentDate.Equals(input.ShipmentDate))
                ) && 
                (
                    this.ShipmentTransactionId == input.ShipmentTransactionId ||
                    (this.ShipmentTransactionId != null &&
                    this.ShipmentTransactionId.Equals(input.ShipmentTransactionId))
                ) && 
                (
                    this.ShipmentId == input.ShipmentId ||
                    (this.ShipmentId != null &&
                    this.ShipmentId.Equals(input.ShipmentId))
                ) && 
                (
                    this.ParcelTrackingNumber == input.ParcelTrackingNumber ||
                    (this.ParcelTrackingNumber != null &&
                    this.ParcelTrackingNumber.Equals(input.ParcelTrackingNumber))
                ) && 
                (
                    this.Carrier == input.Carrier ||
                    (this.Carrier != null &&
                    this.Carrier.Equals(input.Carrier))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.PackageLength == input.PackageLength ||
                    (this.PackageLength != null &&
                    this.PackageLength.Equals(input.PackageLength))
                ) && 
                (
                    this.PackageWidth == input.PackageWidth ||
                    (this.PackageWidth != null &&
                    this.PackageWidth.Equals(input.PackageWidth))
                ) && 
                (
                    this.PackageHeight == input.PackageHeight ||
                    (this.PackageHeight != null &&
                    this.PackageHeight.Equals(input.PackageHeight))
                ) && 
                (
                    this.Weight == input.Weight ||
                    (this.Weight != null &&
                    this.Weight.Equals(input.Weight))
                ) && 
                (
                    this.Zone == input.Zone ||
                    (this.Zone != null &&
                    this.Zone.Equals(input.Zone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentDate != null)
                    hashCode = hashCode * 59 + this.ShipmentDate.GetHashCode();
                if (this.ShipmentTransactionId != null)
                    hashCode = hashCode * 59 + this.ShipmentTransactionId.GetHashCode();
                if (this.ShipmentId != null)
                    hashCode = hashCode * 59 + this.ShipmentId.GetHashCode();
                if (this.ParcelTrackingNumber != null)
                    hashCode = hashCode * 59 + this.ParcelTrackingNumber.GetHashCode();
                if (this.Carrier != null)
                    hashCode = hashCode * 59 + this.Carrier.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.PackageLength != null)
                    hashCode = hashCode * 59 + this.PackageLength.GetHashCode();
                if (this.PackageWidth != null)
                    hashCode = hashCode * 59 + this.PackageWidth.GetHashCode();
                if (this.PackageHeight != null)
                    hashCode = hashCode * 59 + this.PackageHeight.GetHashCode();
                if (this.Weight != null)
                    hashCode = hashCode * 59 + this.Weight.GetHashCode();
                if (this.Zone != null)
                    hashCode = hashCode * 59 + this.Zone.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
