/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// ParcelProtectionPolicyResponseContent
    /// </summary>
    [DataContract]
    public partial class ParcelProtectionPolicyResponseContent :  IEquatable<ParcelProtectionPolicyResponseContent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelProtectionPolicyResponseContent" /> class.
        /// </summary>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="developerId">developerId.</param>
        /// <param name="subscriptionAccNo">subscriptionAccNo.</param>
        /// <param name="clientTransactionId">clientTransactionId.</param>
        /// <param name="policyDetails">policyDetails.</param>
        /// <param name="shipmentDetails">shipmentDetails.</param>
        /// <param name="shipperInfo">shipperInfo.</param>
        /// <param name="consigneeInfo">consigneeInfo.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public ParcelProtectionPolicyResponseContent(string transactionId = default(string), string developerId = default(string), string subscriptionAccNo = default(string), string clientTransactionId = default(string), ParcelProtectionPolicyResponsePolicyDetails policyDetails = default(ParcelProtectionPolicyResponsePolicyDetails), ParcelProtectionPolicyResponseShipmentDetails shipmentDetails = default(ParcelProtectionPolicyResponseShipmentDetails), ParcelProtectionPolicyResponseShipperInfo shipperInfo = default(ParcelProtectionPolicyResponseShipperInfo), ParcelProtectionPolicyResponseShipperInfo consigneeInfo = default(ParcelProtectionPolicyResponseShipperInfo), string createdAt = default(string), string updatedAt = default(string))
        {
            this.TransactionId = transactionId;
            this.DeveloperId = developerId;
            this.SubscriptionAccNo = subscriptionAccNo;
            this.ClientTransactionId = clientTransactionId;
            this.PolicyDetails = policyDetails;
            this.ShipmentDetails = shipmentDetails;
            this.ShipperInfo = shipperInfo;
            this.ConsigneeInfo = consigneeInfo;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }
        
        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name="transactionId", EmitDefaultValue=false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets DeveloperId
        /// </summary>
        [DataMember(Name="developerId", EmitDefaultValue=false)]
        public string DeveloperId { get; set; }

        /// <summary>
        /// Gets or Sets SubscriptionAccNo
        /// </summary>
        [DataMember(Name="subscriptionAccNo", EmitDefaultValue=false)]
        public string SubscriptionAccNo { get; set; }

        /// <summary>
        /// Gets or Sets ClientTransactionId
        /// </summary>
        [DataMember(Name="clientTransactionId", EmitDefaultValue=false)]
        public string ClientTransactionId { get; set; }

        /// <summary>
        /// Gets or Sets PolicyDetails
        /// </summary>
        [DataMember(Name="policyDetails", EmitDefaultValue=false)]
        public ParcelProtectionPolicyResponsePolicyDetails PolicyDetails { get; set; }

        /// <summary>
        /// Gets or Sets ShipmentDetails
        /// </summary>
        [DataMember(Name="shipmentDetails", EmitDefaultValue=false)]
        public ParcelProtectionPolicyResponseShipmentDetails ShipmentDetails { get; set; }

        /// <summary>
        /// Gets or Sets ShipperInfo
        /// </summary>
        [DataMember(Name="shipperInfo", EmitDefaultValue=false)]
        public ParcelProtectionPolicyResponseShipperInfo ShipperInfo { get; set; }

        /// <summary>
        /// Gets or Sets ConsigneeInfo
        /// </summary>
        [DataMember(Name="consigneeInfo", EmitDefaultValue=false)]
        public ParcelProtectionPolicyResponseShipperInfo ConsigneeInfo { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name="createdAt", EmitDefaultValue=false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name="updatedAt", EmitDefaultValue=false)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParcelProtectionPolicyResponseContent {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  DeveloperId: ").Append(DeveloperId).Append("\n");
            sb.Append("  SubscriptionAccNo: ").Append(SubscriptionAccNo).Append("\n");
            sb.Append("  ClientTransactionId: ").Append(ClientTransactionId).Append("\n");
            sb.Append("  PolicyDetails: ").Append(PolicyDetails).Append("\n");
            sb.Append("  ShipmentDetails: ").Append(ShipmentDetails).Append("\n");
            sb.Append("  ShipperInfo: ").Append(ShipperInfo).Append("\n");
            sb.Append("  ConsigneeInfo: ").Append(ConsigneeInfo).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParcelProtectionPolicyResponseContent);
        }

        /// <summary>
        /// Returns true if ParcelProtectionPolicyResponseContent instances are equal
        /// </summary>
        /// <param name="input">Instance of ParcelProtectionPolicyResponseContent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParcelProtectionPolicyResponseContent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransactionId == input.TransactionId ||
                    (this.TransactionId != null &&
                    this.TransactionId.Equals(input.TransactionId))
                ) && 
                (
                    this.DeveloperId == input.DeveloperId ||
                    (this.DeveloperId != null &&
                    this.DeveloperId.Equals(input.DeveloperId))
                ) && 
                (
                    this.SubscriptionAccNo == input.SubscriptionAccNo ||
                    (this.SubscriptionAccNo != null &&
                    this.SubscriptionAccNo.Equals(input.SubscriptionAccNo))
                ) && 
                (
                    this.ClientTransactionId == input.ClientTransactionId ||
                    (this.ClientTransactionId != null &&
                    this.ClientTransactionId.Equals(input.ClientTransactionId))
                ) && 
                (
                    this.PolicyDetails == input.PolicyDetails ||
                    (this.PolicyDetails != null &&
                    this.PolicyDetails.Equals(input.PolicyDetails))
                ) && 
                (
                    this.ShipmentDetails == input.ShipmentDetails ||
                    (this.ShipmentDetails != null &&
                    this.ShipmentDetails.Equals(input.ShipmentDetails))
                ) && 
                (
                    this.ShipperInfo == input.ShipperInfo ||
                    (this.ShipperInfo != null &&
                    this.ShipperInfo.Equals(input.ShipperInfo))
                ) && 
                (
                    this.ConsigneeInfo == input.ConsigneeInfo ||
                    (this.ConsigneeInfo != null &&
                    this.ConsigneeInfo.Equals(input.ConsigneeInfo))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionId != null)
                    hashCode = hashCode * 59 + this.TransactionId.GetHashCode();
                if (this.DeveloperId != null)
                    hashCode = hashCode * 59 + this.DeveloperId.GetHashCode();
                if (this.SubscriptionAccNo != null)
                    hashCode = hashCode * 59 + this.SubscriptionAccNo.GetHashCode();
                if (this.ClientTransactionId != null)
                    hashCode = hashCode * 59 + this.ClientTransactionId.GetHashCode();
                if (this.PolicyDetails != null)
                    hashCode = hashCode * 59 + this.PolicyDetails.GetHashCode();
                if (this.ShipmentDetails != null)
                    hashCode = hashCode * 59 + this.ShipmentDetails.GetHashCode();
                if (this.ShipperInfo != null)
                    hashCode = hashCode * 59 + this.ShipperInfo.GetHashCode();
                if (this.ConsigneeInfo != null)
                    hashCode = hashCode * 59 + this.ConsigneeInfo.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.UpdatedAt != null)
                    hashCode = hashCode * 59 + this.UpdatedAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
