/* 
 * Shipping API
 *
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pitneyBower.Client.OpenAPIDateConverter;

namespace pitneyBower.Model
{
    /// <summary>
    /// ParcelProtectionQuoteRequestShipmentInfoShipperInfo
    /// </summary>
    [DataContract]
    public partial class ParcelProtectionQuoteRequestShipmentInfoShipperInfo :  IEquatable<ParcelProtectionQuoteRequestShipmentInfoShipperInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelProtectionQuoteRequestShipmentInfoShipperInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ParcelProtectionQuoteRequestShipmentInfoShipperInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelProtectionQuoteRequestShipmentInfoShipperInfo" /> class.
        /// </summary>
        /// <param name="shipperID">shipperID (required).</param>
        /// <param name="address">address (required).</param>
        public ParcelProtectionQuoteRequestShipmentInfoShipperInfo(string shipperID = default(string), ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress address = default(ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress))
        {
            // to ensure "shipperID" is required (not null)
            if (shipperID == null)
            {
                throw new InvalidDataException("shipperID is a required property for ParcelProtectionQuoteRequestShipmentInfoShipperInfo and cannot be null");
            }
            else
            {
                this.ShipperID = shipperID;
            }
            
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new InvalidDataException("address is a required property for ParcelProtectionQuoteRequestShipmentInfoShipperInfo and cannot be null");
            }
            else
            {
                this.Address = address;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets ShipperID
        /// </summary>
        [DataMember(Name="shipperID", EmitDefaultValue=true)]
        public string ShipperID { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=true)]
        public ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParcelProtectionQuoteRequestShipmentInfoShipperInfo {\n");
            sb.Append("  ShipperID: ").Append(ShipperID).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParcelProtectionQuoteRequestShipmentInfoShipperInfo);
        }

        /// <summary>
        /// Returns true if ParcelProtectionQuoteRequestShipmentInfoShipperInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ParcelProtectionQuoteRequestShipmentInfoShipperInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParcelProtectionQuoteRequestShipmentInfoShipperInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ShipperID == input.ShipperID ||
                    (this.ShipperID != null &&
                    this.ShipperID.Equals(input.ShipperID))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipperID != null)
                    hashCode = hashCode * 59 + this.ShipperID.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
